<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>my-kbb_hydrated-ews-fe7-68a</name>
   <tag></tag>
   <elementGuidId>db2ba6ad-7c63-4ada-abeb-b4c2baead2ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>my-kbb.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>my-kbb</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>my-kbb</value>
      <webElementGuid>b4a9d442-4376-4cf9-af3c-2e67a82e84b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>55491526-bfeb-4039-94f4-f2ccd79e607a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/my-kbb[@class=&quot;hydrated&quot;]</value>
      <webElementGuid>97de83f2-6dcf-4d40-93f1-74c067777160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KBB/Page_Kelley Blue Book  New and Used Car Pri_e90311/user-profile_Recalls_hydrated-Reviews-fe7</value>
      <webElementGuid>ff1308c0-db69-430c-899b-536b5d4467e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e2e41cb1-bb92-472a-8086-39372e051afc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
