<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Get My Cars Value</name>
   <tag></tag>
   <elementGuidId>dc834630-d262-405b-a2ec-32a96f75bd70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stepModuleContainer']/div/div/span/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.css-xdfkee.e1uau9z01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Get My Car's Value&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06425486-ec8d-4b7a-8769-07930e5cf256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c7c935b5-4168-4a9a-b4ae-3236ef315ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-xdfkee e1uau9z01</value>
      <webElementGuid>c238f672-db8d-4c3a-94b5-e92d1405a188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get My Car's Value</value>
      <webElementGuid>b8b68983-e169-4f7c-9c45-a4fee5659bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepModuleContainer&quot;)/div[@class=&quot;css-td2030 e6p01070&quot;]/div[@class=&quot;css-13rh4em etn5x2f11&quot;]/span[1]/a[@class=&quot;css-45epp7 e1uau9z02&quot;]/span[@class=&quot;css-xdfkee e1uau9z01&quot;]</value>
      <webElementGuid>ad1174d8-4feb-481b-b9bf-3b6189012d3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stepModuleContainer']/div/div/span/a/span</value>
      <webElementGuid>c3c10dc7-92d8-46c7-8c75-1d5ee717d9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start with Your Current Car'])[1]/following::span[2]</value>
      <webElementGuid>f636f3c9-22f4-4979-a9fb-d2e978a45ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Let Kelley Help You Shop Like a Pro'])[1]/following::span[5]</value>
      <webElementGuid>c923ec75-9b8e-44fc-9b3d-e6a46c515984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended for You'])[1]/preceding::span[1]</value>
      <webElementGuid>19a61f10-39ac-43c8-96bb-e1c1736a44d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starting Price'])[1]/preceding::span[2]</value>
      <webElementGuid>b736e793-791e-49c9-add6-65a08ede5ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/span</value>
      <webElementGuid>12714e13-8796-4ea6-a1a5-e25a74589440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot;Get My Car&quot; , &quot;'&quot; , &quot;s Value&quot;) or . = concat(&quot;Get My Car&quot; , &quot;'&quot; , &quot;s Value&quot;))]</value>
      <webElementGuid>df2ee25b-efa6-45ae-913a-f32889411bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
