<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user-profile_Recalls_hydrated-Reviews-fe7</name>
   <tag></tag>
   <elementGuidId>3518f567-b87f-41a3-a95b-6049dfa484bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/header/div/div[2]/user-profile-hydrator/user-profile</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>user-profile.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>user-profile</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>user-profile</value>
      <webElementGuid>29b4f27d-0283-45d7-8d9c-1b978a4f43a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>location-zipcode</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>a8293aab-fb3f-4c98-b1d3-a59bb561f954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>slim</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>07d40b91-b240-482b-9bab-4528079912de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>8b94b590-e9e4-45e9-8873-2d314a1d27cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/header[@class=&quot;css-kzuwlq&quot;]/div[@class=&quot;css-5m0t2j&quot;]/div[@class=&quot;css-157yk1y&quot;]/user-profile-hydrator[@class=&quot;hydrated&quot;]/user-profile[@class=&quot;hydrated&quot;]</value>
      <webElementGuid>a81fb1a3-09ac-44fd-a898-c6063ea61aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/header/div/div[2]/user-profile-hydrator/user-profile</value>
      <webElementGuid>4786c23f-04ed-4772-af9d-1bfaa403e371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//user-profile</value>
      <webElementGuid>3c5c0f76-b440-4fec-a8cd-c6a0741fa84e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
