<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_eSPORTS</name>
   <tag></tag>
   <elementGuidId>58bac4ca-8f89-4983-a08b-f75a2a8cef71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;eSPORT&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='admWrapsite']/div/div/div/div[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;eSPORTS&quot;s] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a68548f4-026c-4875-aca2-30a7e8f7eb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>eSPORT</value>
      <webElementGuid>af1a2331-1fb3-49bb-87e5-1a3e8de04ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/esport.chn</value>
      <webElementGuid>3a48dff2-c8b1-4740-99cf-fb1360809da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>eSPORTS</value>
      <webElementGuid>93bee6a6-31e4-4c43-bc03-34956ddad3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admWrapsite&quot;)/div[@class=&quot;wp1000 wfull&quot;]/div[@class=&quot;wp1000&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;menu&quot;]/ul[1]/li[@class=&quot;normal&quot;]/a[1]</value>
      <webElementGuid>16aab870-500c-42cf-a805-5bb4787190e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div/div/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>a7efd63f-e54f-4997-8ac2-db9e6f0c448f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'eSPORTS')]</value>
      <webElementGuid>5230ca50-244c-4425-b0e0-7f603bcec569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GAME MOBILE'])[1]/following::a[1]</value>
      <webElementGuid>720bfccc-12f3-4fdd-affe-1a0d34130ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KHÁM PHÁ'])[1]/preceding::a[1]</value>
      <webElementGuid>cf8ba1af-bd27-4a07-92c2-bb6549cf1623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANGA/FILM'])[1]/preceding::a[2]</value>
      <webElementGuid>75fddf1f-b515-48f4-99d7-f5f6a404dac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='eSPORTS']/parent::*</value>
      <webElementGuid>3bf35398-6478-499f-b612-f849c9276d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/esport.chn')]</value>
      <webElementGuid>8ab2baed-3625-44ff-9986-3d53a1e8ad49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>e09a581a-7f51-45ea-877e-bcac81c87459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'eSPORT' and @href = '/esport.chn' and (text() = 'eSPORTS' or . = 'eSPORTS')]</value>
      <webElementGuid>1e6f60d4-19a0-4310-9195-7c78d44a2863</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
