<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_RSS_mb10</name>
   <tag></tag>
   <elementGuidId>f12c6d7a-b860-40c4-9d11-6f737a108a5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mb10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='admWrapsite']/div[2]/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Công ty cổ phần VCCorp&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>698068a8-337a-4f3f-9038-81eaaec7c0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vccorp.mediacdn.vn/vccorp-s.png</value>
      <webElementGuid>969e62ba-5593-458c-8796-99a105c8c9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Công ty cổ phần VCCorp</value>
      <webElementGuid>4072f903-ed77-4658-bd6b-904fa7b33552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb10</value>
      <webElementGuid>4e5aabad-dfe6-4175-b545-976cec637835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admWrapsite&quot;)/div[@class=&quot;footer fl&quot;]/div[@class=&quot;info&quot;]/div[@class=&quot;wp980-mauto&quot;]/div[@class=&quot;left_info&quot;]/a[1]/img[@class=&quot;mb10&quot;]</value>
      <webElementGuid>38d42447-f93d-402b-bb5e-99d717ba04d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div[2]/div[2]/div/div/a/img</value>
      <webElementGuid>5c5634b4-7e3c-4e3c-a0b2-afccf34e6cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Công ty cổ phần VCCorp']</value>
      <webElementGuid>2dd472e2-2e2b-49c8-b331-61a6c5726393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/a/img</value>
      <webElementGuid>c78a7751-e860-4ad5-bf3e-57950d2fe0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://vccorp.mediacdn.vn/vccorp-s.png' and @alt = 'Công ty cổ phần VCCorp']</value>
      <webElementGuid>8a676cd8-11dd-4f2f-a869-e8f43fce6d4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
