<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_SOLUTIONS</name>
   <tag></tag>
   <elementGuidId>6503135e-2b1a-4e03-afb7-74b0b5e00a13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Your Project'])[1]/following::h5[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;SOLUTIONS&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>15d8efa9-ea91-4ff5-aeaf-c9c168baf825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SOLUTIONS</value>
      <webElementGuid>0752b3a0-4a75-42dc-bc5d-e8ddc1904a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-templates page-template-default-2024 page-template-page-templatesdefault-2024-php page page-id-7681 mega-menu-primary  notMobile   isDesktop  no-sidebar wpb-js-composer js-comp-ver-7.6 vc_responsive&quot;]/footer[@class=&quot;site-footer&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;vc_row wpb_row vc_row-fluid vc_column-gap-20 vc_row-o-equal-height vc_row-flex menu&quot;]/div[@class=&quot;footer-col-1 wpb_column vc_col-md-6 vc_col-xs-12 footer-col-one&quot;]/h5[1]</value>
      <webElementGuid>0b2e4945-f428-47ae-b6e3-ed21d281db57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Your Project'])[1]/following::h5[1]</value>
      <webElementGuid>fdc7f8d5-6a67-4a43-a880-489b2456d9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AI &amp; Machine Learning'])[3]/preceding::h5[1]</value>
      <webElementGuid>a2e3ab14-8eb7-48fa-adcd-147444117990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud Migration'])[3]/preceding::h5[1]</value>
      <webElementGuid>e716f4c0-835a-41e0-8d22-8a7b84762da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SOLUTIONS']/parent::*</value>
      <webElementGuid>1e0ed479-6671-40fb-9f3a-9e65110fc6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>05ad4573-1d2e-4324-896d-5f2c3f8e2c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'SOLUTIONS' or . = 'SOLUTIONS')]</value>
      <webElementGuid>c6c1e13c-8e16-4a76-bde4-be7a64dd9ccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
