<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Accept All_mega-menu-logo</name>
   <tag></tag>
   <elementGuidId>f68d4a14-d9b4-40b2-9a30-3aab47a0165a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mega-menu-item-10810']/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mega-menu-link.mega-menu-logo > img.mega-menu-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mega-menu-item-10810 >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>873efd44-8176-45f9-8243-21b6835299f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mega-menu-logo</value>
      <webElementGuid>cdd4dfcc-7479-46d2-9eb0-92e847f4eb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>114</value>
      <webElementGuid>9bd23f28-1c0a-4ce6-8c31-f493a8530228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>925cd1ad-453a-4350-ad30-8910b90f271f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kms-technology.com/wp-content/uploads/2022/03/logo-white.svg</value>
      <webElementGuid>8dcec49c-aece-45dc-b93a-2e335820c3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mega-menu-item-10810&quot;)/a[@class=&quot;mega-menu-link mega-menu-logo&quot;]/img[@class=&quot;mega-menu-logo&quot;]</value>
      <webElementGuid>c8c264f5-3c22-419b-847f-ef724e42f78d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mega-menu-item-10810']/a/img</value>
      <webElementGuid>584be881-2bbe-4378-898f-7b3c2c919cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://kms-technology.com/wp-content/uploads/2022/03/logo-white.svg')]</value>
      <webElementGuid>9fc17d9b-c22a-48e1-a37e-52c65496e1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>ea17017c-c715-4ab4-9ee3-6de4391dc863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kms-technology.com/wp-content/uploads/2022/03/logo-white.svg']</value>
      <webElementGuid>a42a2f03-c871-4423-8892-df858928e9c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
