<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_eSPORTS</name>
   <tag></tag>
   <elementGuidId>7fa0c742-eb44-40b7-bcac-0dbee08dd812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;eSPORT&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='admWrapsite']/div/div/div/div[2]/ul/li[3]/h1/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;eSPORTS&quot;s] >> internal:attr=[title=&quot;eSPORT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4cb10a9-b303-4338-8272-a7688126515e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>eSPORT</value>
      <webElementGuid>7bb6a78b-0dab-45f2-9b04-c063fc114939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/esport.chn</value>
      <webElementGuid>10d16d2b-124b-42af-89b9-8f8d0c64ecf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>eSPORTS</value>
      <webElementGuid>ceb5f58c-eddc-4f7b-babe-90ee07868eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admWrapsite&quot;)/div[@class=&quot;wp1000 wfull&quot;]/div[@class=&quot;wp1000&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;menu&quot;]/ul[1]/li[@class=&quot;normal active&quot;]/h1[1]/a[1]</value>
      <webElementGuid>d77eb1a0-d2b4-4e90-924d-31098d886ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div/div/div/div[2]/ul/li[3]/h1/a</value>
      <webElementGuid>07cb4134-e1d1-4275-8b93-7787e1a64616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'eSPORTS')]</value>
      <webElementGuid>e023e8be-df9b-4613-be11-1bd162ea3ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GAME MOBILE'])[1]/following::a[1]</value>
      <webElementGuid>5ee926e9-e6d8-493e-bfff-f3e1240185d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KHÁM PHÁ'])[1]/preceding::a[1]</value>
      <webElementGuid>4ebc21d3-ed25-4fa8-b640-92f0427d2b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANGA/FILM'])[1]/preceding::a[2]</value>
      <webElementGuid>ba33f2bb-ea5e-411d-98eb-49ce056edeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='eSPORTS']/parent::*</value>
      <webElementGuid>fb9280b1-2f92-4596-81db-d42e68590003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/esport.chn')]</value>
      <webElementGuid>71d6f704-06e7-4fcc-9294-4463a4c1fe0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/a</value>
      <webElementGuid>c801e1bc-01d4-4d50-aedd-17997f1e5892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'eSPORT' and @href = '/esport.chn' and (text() = 'eSPORTS' or . = 'eSPORTS')]</value>
      <webElementGuid>1c78a047-4552-4fbd-b470-5581a007d577</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
