<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sign In_display-inline-block display-lg-none</name>
   <tag></tag>
   <elementGuidId>1ee30687-ce09-4647-83ad-106a2f5bcf30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mountNode']/header/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.display-inline-block.display-lg-none</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Find Cars for Sale at Autotrader&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f3630ea8-de70-4a5a-a23d-4cc3174ebf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>display-inline-block display-lg-none</value>
      <webElementGuid>42ddbf78-2d8a-4fc0-9f23-06612e05dcb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//www.autotrader.com/content/static/img/icon/logos/atc-logo.svg</value>
      <webElementGuid>55e27a75-b7e7-428c-a98f-0c1fab4b6eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>703b87b8-6259-458a-b57a-03ebfcfece1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>d4541923-8f6f-4052-acf0-dd5727eebd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>ccdabaf5-9a50-4960-bda4-0f36b62b9017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountNode&quot;)/header[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;navbar-wrapper&quot;]/a[@class=&quot;header-brand&quot;]/img[@class=&quot;display-inline-block display-lg-none&quot;]</value>
      <webElementGuid>9a43ad35-a5d1-4592-a31e-cedbcbad4c4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountNode']/header/div/div/a/img</value>
      <webElementGuid>473b28e0-7e60-4c0c-8f35-5fc9e89a78d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3b379536-65b8-4c8b-bbd8-f4ea807128d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//www.autotrader.com/content/static/img/icon/logos/atc-logo.svg']</value>
      <webElementGuid>d4670b22-9aba-4cf4-a708-b9dafc8ba33a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
