<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact us</name>
   <tag></tag>
   <elementGuidId>da133bc2-113e-4214-b662-b640a7feaf6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div/div/div/div/ul/li/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Contact Us&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e2d42a0-d816-435a-81e5-d8539b9c164d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/contact-us</value>
      <webElementGuid>dc891a77-1280-40ab-8aa2-5f6c8fa49d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Us</value>
      <webElementGuid>99124d23-8504-4e9f-ad13-91068562c8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;component fsoft-container&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;component fsoft-container bgr-black header-container-first&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;component link-list header-link-list&quot;]/div[@class=&quot;component-content&quot;]/ul[1]/li[@class=&quot;item0 odd first&quot;]/div[@class=&quot;field-link&quot;]/a[1]</value>
      <webElementGuid>15961d06-b17a-4353-89a0-a1afa39232d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variantitemid</name>
      <type>Main</type>
      <value>{42F47986-34F6-44A5-A153-5F25083F4B33}</value>
      <webElementGuid>c52e834b-fb22-46b1-a8d3-c9202cd6f113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variantfieldname</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>44181ef5-a8bb-4820-8020-387439a48dd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div/div/div/div/ul/li/div/a</value>
      <webElementGuid>06ec835e-9fff-4210-8008-81cb6df71a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Contact Us')]</value>
      <webElementGuid>bcc9525c-f740-4f58-bf5c-33aee5f7aa6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career'])[1]/preceding::a[1]</value>
      <webElementGuid>d1a8ae6a-0495-427f-83df-ee62f7fde007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsroom'])[1]/preceding::a[2]</value>
      <webElementGuid>e4ff4f61-ea5f-40c5-bafd-d189b9fec996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contact Us']/parent::*</value>
      <webElementGuid>aaa3f13f-2901-4d65-a4e2-a2c327babb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/contact-us')]</value>
      <webElementGuid>f82bf8ee-fb98-464f-bdcd-db6f9e0c85b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>8d12e0e1-54bd-419e-8e7a-3cde925483ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/contact-us' and (text() = 'Contact Us' or . = 'Contact Us')]</value>
      <webElementGuid>24a0ed83-f40c-4de0-8940-6e1aa6192451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer']/div/div/div/div/div/div/div/div/nav/ul/li[5]/a</value>
      <webElementGuid>d806f490-50bc-4806-ab38-b980ac093307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Contact us')])[2]</value>
      <webElementGuid>cc948786-6b8e-44c0-b997-125c28b4d7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OUR ResourceS Center'])[1]/following::a[1]</value>
      <webElementGuid>42cf3bf2-da66-4393-a085-f0e05160381b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsroom'])[7]/following::a[2]</value>
      <webElementGuid>c082d3ae-9d07-4a54-ad21-51276ba974e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONNECT WITH US'])[1]/preceding::a[1]</value>
      <webElementGuid>22d73ce0-212b-49d2-b0ad-b2cbfe813b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of use'])[1]/preceding::a[6]</value>
      <webElementGuid>17fd7886-e19d-43ef-999d-23adf02cc5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/contact-us')])[4]</value>
      <webElementGuid>45fefc9e-a0fd-463c-8e24-21a43a8e7dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[5]/a</value>
      <webElementGuid>ef61a085-3b47-42c7-80f2-c6e860b1d4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/contact-us' and (text() = 'Contact us' or . = 'Contact us')]</value>
      <webElementGuid>57943363-4923-454b-a684-1d9ac8225ae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
