<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Events</name>
   <tag></tag>
   <elementGuidId>acb97a9c-91c3-40b2-b664-80daf05a3859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div/div/div/div/ul/li[4]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.item3.even.last > div.field-link > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Events&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec7ad9a0-d8f1-4998-b394-29f18b043495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/newsroom/event-calendar</value>
      <webElementGuid>e0ec975c-ff00-4ef0-8118-ad05bfb2a2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variantitemid</name>
      <type>Main</type>
      <value>{8FB06C5B-9838-469C-A910-913F9FDD5C23}</value>
      <webElementGuid>0c82c16e-6a28-4e6e-86a2-f0da42a4b236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variantfieldname</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>70a9e002-b8b8-4cae-9994-db7f03a645a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Events</value>
      <webElementGuid>f6216c8d-61c9-4ae5-afe0-ff4fbf9db851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;component fsoft-container&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;component fsoft-container bgr-black header-container-first&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;component link-list header-link-list&quot;]/div[@class=&quot;component-content&quot;]/ul[1]/li[@class=&quot;item3 even last&quot;]/div[@class=&quot;field-link&quot;]/a[1]</value>
      <webElementGuid>c667b195-dba1-41d3-9128-a9cde1a2cbe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div/div/div/div/ul/li[4]/div/a</value>
      <webElementGuid>387810f3-88bc-4e68-990c-b63de18eec3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Events')]</value>
      <webElementGuid>885ad806-c6ee-4b35-b233-6a10329b37e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsroom'])[1]/following::a[1]</value>
      <webElementGuid>f1c917b0-9ed8-430b-9812-c291be52628b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career'])[1]/following::a[2]</value>
      <webElementGuid>2817ace4-d491-4d56-a745-253eaeb73706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Global'])[1]/preceding::a[1]</value>
      <webElementGuid>87cacfbb-613c-4978-a0bf-05ea68b155af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Global (English)'])[1]/preceding::a[2]</value>
      <webElementGuid>a226a76a-32a7-407f-8c19-b715e5985e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Events']/parent::*</value>
      <webElementGuid>be19bddf-f25c-4d79-a1e9-852064e66926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/newsroom/event-calendar')]</value>
      <webElementGuid>4afef5b4-962d-490b-bb04-e320967bb6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a</value>
      <webElementGuid>44130dd8-b9f6-477e-9364-e8f436db7c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/newsroom/event-calendar' and (text() = 'Events' or . = 'Events')]</value>
      <webElementGuid>603f790c-182a-40ca-9751-326846a433e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
