<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Industries</name>
   <tag></tag>
   <elementGuidId>1234fcf9-1aaa-4d91-910e-ddea04df9a4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div[2]/div/div[3]/div/nav/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.rel-level1.grid-content.level1.submenu.item2.odd.nav-main__first--li.has-sub > a.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#header >> internal:role=navigation >> internal:role=link[name=&quot;Industries&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>60106f1e-8c8f-4e63-8d01-7254baad53c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>571a5398-8b47-413b-b370-7d88b021382b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover-target</name>
      <type>Main</type>
      <value>{17D2F13D-15F7-4E56-87BC-201541E96690}</value>
      <webElementGuid>2425d2ee-1631-49d4-9f7d-2c2feadd8b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-page-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>91eab7ed-642d-4578-8b2e-f78ee7fbac5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>4fed8d56-5f51-43bb-ba34-de5f05eba5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
    Industries
</value>
      <webElementGuid>389152cc-acc2-4e2a-ba93-a0daf362c625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;component fsoft-container&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;component fsoft-container bgr-white header-container-second&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;component main-navigation&quot;]/div[@class=&quot;component-content&quot;]/nav[@class=&quot;nav-main&quot;]/ul[@class=&quot;nav-main__menu d-flex align-items-center&quot;]/li[@class=&quot;rel-level1 grid-content level1 submenu item2 odd nav-main__first--li has-sub&quot;]/a[@class=&quot;active&quot;]</value>
      <webElementGuid>290f3e39-c547-4458-afb5-b2ed7dda97e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div[2]/div/div[3]/div/nav/ul/li[3]/a</value>
      <webElementGuid>7f29ade9-e8e6-401f-9cb4-c2ee74205226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Industries')]</value>
      <webElementGuid>e851499a-0328-493e-b899-4f9aab96a81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experience Design (UX/UI/3D)'])[1]/following::a[1]</value>
      <webElementGuid>dce9d169-0a44-4611-b973-2a3e7bb21f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automotive'])[1]/preceding::a[1]</value>
      <webElementGuid>ebbaa195-019d-4079-b64f-5db5a8798679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturing'])[1]/preceding::a[2]</value>
      <webElementGuid>7ed42324-e10c-4878-89da-2ab1c5105359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Industries']/parent::*</value>
      <webElementGuid>726ef386-a957-4692-994e-c4569e82e8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[8]</value>
      <webElementGuid>d5bcef76-c0c9-4def-909e-478d30e6610b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a</value>
      <webElementGuid>6c4ec4e9-d89f-4eec-803a-d2158d7a0c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = ' 
    Industries
' or . = ' 
    Industries
')]</value>
      <webElementGuid>a5f1bf2b-ca3e-495e-876e-6d6585e4ebc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
