<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Services</name>
   <tag></tag>
   <elementGuidId>94255364-ad86-43d9-ad3f-f5fff5b54eba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div[2]/div/div[3]/div/nav/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#header >> internal:role=navigation >> internal:role=link[name=&quot;Services&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70cd7228-f5ce-467d-97b3-cfb915a8f8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>b01b32f1-64a3-40c5-9825-bf36c35835b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover-target</name>
      <type>Main</type>
      <value>{359DD0C4-D050-4501-8223-325FE39D71C7}</value>
      <webElementGuid>f3fa2dc8-81fa-4641-8839-a6ccd65b71cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-page-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3c423247-5173-48a6-b6aa-ea108996ad65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>8aaf1d58-89d5-4add-89c4-55d9d9f57e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
    Services
</value>
      <webElementGuid>39f50391-2333-4636-9892-8ac90a9fb139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;component fsoft-container&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;component fsoft-container bgr-white header-container-second&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;component main-navigation&quot;]/div[@class=&quot;component-content&quot;]/nav[@class=&quot;nav-main&quot;]/ul[@class=&quot;nav-main__menu d-flex align-items-center&quot;]/li[@class=&quot;rel-level1 side-content level1 submenu item1 even nav-main__first--li has-sub&quot;]/a[@class=&quot;active&quot;]</value>
      <webElementGuid>bab56dd6-0125-4c4b-98d2-52e850f37d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div[2]/div/div[3]/div/nav/ul/li[2]/a</value>
      <webElementGuid>99ad4fc0-74c9-4ce2-a05a-51af6cfb7385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Services')]</value>
      <webElementGuid>6821ad6a-a0f3-429b-9aec-9dadcf95627e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accompany You on Your Transformation Journey'])[1]/following::a[1]</value>
      <webElementGuid>3a7c85f6-e3fe-4d76-abea-6bcf85696df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore (English)'])[1]/following::a[3]</value>
      <webElementGuid>5689fe2a-15ab-4093-90c0-1a998d8a9767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT Strategic Consultancy'])[1]/preceding::a[1]</value>
      <webElementGuid>fc71699b-9bbe-47b9-8f6c-2bfbafce51e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Technologies &amp; Platforms'])[1]/preceding::a[2]</value>
      <webElementGuid>92153bd2-ad61-4467-a84f-0eeaa5b08eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Services']/parent::*</value>
      <webElementGuid>531e9b3e-58ca-4ae8-a9be-18be32045f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>fced8521-06c2-4caa-bb0b-26c4be0b8fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>ce76bc3a-473f-4045-81b9-0c74588705ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = ' 
    Services
' or . = ' 
    Services
')]</value>
      <webElementGuid>8f8b41e1-7744-4239-8a46-9d79e2346c0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
