<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Singapore (English)_img-logo</name>
   <tag></tag>
   <elementGuidId>3b578f12-977a-40b8-8aaf-eff22aae0269</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.component-content > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>78330bf3-66c6-40e6-8fdc-df2a54645ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/-/media/project/fpt-software/fso/systems/logo/logo.svg?as=1&amp;iar=0&amp;extension=webp&amp;modified=20230519141554&amp;hash=A28FD0836414E4F10707ECCC57D396B2</value>
      <webElementGuid>18aa800c-67aa-467a-94f6-89879cab4dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-logo</value>
      <webElementGuid>f4a40a40-3d54-48a0-a458-7a13697208b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>db9d8063-d14d-40e8-a141-6f48a8273d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;component fsoft-container&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;component fsoft-container bgr-white header-container-second&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;component image&quot;]/div[@class=&quot;component-content&quot;]/a[1]/img[@class=&quot;img-logo&quot;]</value>
      <webElementGuid>7816a1da-a569-4e44-bb71-91ad9e425c74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>426f7890-2d7c-4a3d-a843-900665a960e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>0b2d9bb4-3c40-459f-b14e-26de3ec0fb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/-/media/project/fpt-software/fso/systems/logo/logo.svg?as=1&amp;iar=0&amp;extension=webp&amp;modified=20230519141554&amp;hash=A28FD0836414E4F10707ECCC57D396B2']</value>
      <webElementGuid>10813166-d0c9-47d4-b200-48b31d847dba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
