<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Our services</name>
   <tag></tag>
   <elementGuidId>342fe60d-de0f-456d-a680-b2c8c1b79e82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='our-services']/div/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.our-service-slider__heading-subtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Our services&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>223cf4eb-a674-4247-bc74-704572c97417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>our-service-slider__heading-subtitle</value>
      <webElementGuid>ab7e03f8-fd93-47c1-a12d-96f16d344223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Our services</value>
      <webElementGuid>791ac19b-3e9f-4717-a6c2-db9b6bf5cf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;our-services&quot;)/div[@class=&quot;component-content&quot;]/div[@class=&quot;component slider our-service px-3 px-md-0&quot;]/div[@class=&quot;component-content&quot;]/div[@class=&quot;our-service-slider container-full-grid&quot;]/div[@class=&quot;our-service-slider__heading col-lg-6 col-xxl-5&quot;]/span[@class=&quot;our-service-slider__heading-subtitle&quot;]</value>
      <webElementGuid>bc6e7467-7b88-4fca-9e72-249ff3f50866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='our-services']/div/div/div/div/div/span</value>
      <webElementGuid>b6113193-2127-499e-a449-4e416e9a2fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Mission'])[1]/following::span[1]</value>
      <webElementGuid>97b85448-b1f0-4900-99af-50516a220399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Speed, Scale, Global Presence, Quality and Compliance.'])[1]/following::span[1]</value>
      <webElementGuid>1bc57fec-f868-4803-9eed-60fe449a3d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accompany clients through every step of the digital journey.'])[1]/preceding::span[1]</value>
      <webElementGuid>55a8a006-d8f5-4efd-8be0-4c9766c433bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stay Current with the Latest Technology Trends'])[1]/preceding::span[2]</value>
      <webElementGuid>5a202d1e-0eb2-435e-874f-f00602617fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Our services']/parent::*</value>
      <webElementGuid>457f5a66-a4e2-455e-9132-cb07b103ab7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/span</value>
      <webElementGuid>ba41e45a-c0cd-45a6-8c94-59041fdeefa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Our services' or . = 'Our services')]</value>
      <webElementGuid>72cb0cdb-af55-4ebf-8a9f-d6580f43d0d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
