<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kelley Knows CarsFrom values to repairs_2ed6c9</name>
   <tag></tag>
   <elementGuidId>4ae31f3b-e80a-431a-a592-7d0051e24cb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='superHeroBannerContainer']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.emdpnlj4.css-18eyk9p.e11el9oi0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Kelley Knows CarsFrom values to repairs, we've got it all.Price New/UsedMy Car's&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0702ffdc-3070-4c32-915e-9f7848ea9c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lean-auto</name>
      <type>Main</type>
      <value>green-monster-0</value>
      <webElementGuid>d422928d-4de3-44f1-8003-66e3c437b76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>emdpnlj4 css-18eyk9p e11el9oi0</value>
      <webElementGuid>90faa45c-4162-4cee-8d33-1366075b89a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelley Knows CarsFrom values to repairs, we've got it all.Price New/UsedMy Car's ValueShop Cars for Sale</value>
      <webElementGuid>cebdabed-9c4d-44e2-9300-77a21fb4e46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;superHeroBannerContainer&quot;)/div[@class=&quot;emdpnlj4 css-18eyk9p e11el9oi0&quot;]</value>
      <webElementGuid>5e70cb31-09a2-4596-a4b6-a939a02eb029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='superHeroBannerContainer']/div[2]</value>
      <webElementGuid>49a01ea5-694e-44ab-ae05-ada97ccc9c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recalls'])[1]/following::div[7]</value>
      <webElementGuid>80f3c28d-447b-45ea-a66c-473ea3a5cbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extended Warranty'])[1]/following::div[7]</value>
      <webElementGuid>42ab69cc-db24-4b46-bc8a-026a54b5d223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[2]</value>
      <webElementGuid>22702d5e-3061-4cfc-a97c-b9a0b87bf5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Kelley Knows CarsFrom values to repairs, we&quot; , &quot;'&quot; , &quot;ve got it all.Price New/UsedMy Car&quot; , &quot;'&quot; , &quot;s ValueShop Cars for Sale&quot;) or . = concat(&quot;Kelley Knows CarsFrom values to repairs, we&quot; , &quot;'&quot; , &quot;ve got it all.Price New/UsedMy Car&quot; , &quot;'&quot; , &quot;s ValueShop Cars for Sale&quot;))]</value>
      <webElementGuid>6ae76f08-7681-4bf2-9683-425682c31bb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
