<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a22e19fc-ead5-47c4-b105-33d7db878591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/header/div/div/a/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Kelley Blue Book. Official Guide. The trusted Resource. Homepage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Kelley Blue Book. Official Guide. The trusted Resource. Homepage&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cf198ce4-6ee4-48d5-9837-119fdfc9fb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>80px</value>
      <webElementGuid>840f8b2b-e5ca-442e-b136-9aeebdc0ad00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>57px</value>
      <webElementGuid>40871b7a-db83-4c34-be6b-89541c7ebe0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://file.kbb.com/kbb/images/logos/KBBLogoRefresh.svg</value>
      <webElementGuid>bf1178ae-c62d-41db-a50b-62a00c9d22b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Kelley Blue Book. Official Guide. The trusted Resource. Homepage</value>
      <webElementGuid>7231f46e-80bb-4587-aa7e-4aa8f1e16265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/header[@class=&quot;css-kzuwlq&quot;]/div[@class=&quot;css-5m0t2j&quot;]/div[@class=&quot;css-y0rk70&quot;]/a[@class=&quot;css-19u26w1 e1ez57g00&quot;]/div[@class=&quot;css-zjik7 eouvoih0&quot;]/div[@class=&quot;css-1rbex4p evaok8f0&quot;]/img[1]</value>
      <webElementGuid>cba8630a-0981-41be-ab92-8438870cb9f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/header/div/div/a/div/div/img</value>
      <webElementGuid>b610ddc7-81af-495c-a922-c4d245bffe23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Kelley Blue Book. Official Guide. The trusted Resource. Homepage']</value>
      <webElementGuid>0652b5e2-5fbb-4010-9e10-4bc8e3965a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4ff4770e-b389-4cf5-9f85-24ad78441f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://file.kbb.com/kbb/images/logos/KBBLogoRefresh.svg' and @alt = 'Kelley Blue Book. Official Guide. The trusted Resource. Homepage']</value>
      <webElementGuid>6ef78472-9c47-41fa-8271-ab23cc4d5250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
