<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Price NewUsed</name>
   <tag></tag>
   <elementGuidId>d00196f4-0a17-43df-8c88-121ee77a00b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='superHeroBannerContainer']/div[2]/div/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.css-hwgv0r.e1uau9z01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Price New/Used&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f10e3c84-67f7-4be5-9102-517045eaac0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>0ae19e0c-3577-41ea-b342-e12355ae3d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-hwgv0r e1uau9z01</value>
      <webElementGuid>f3a989b1-928b-4e6d-b3cf-f21a166cfc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Price New/Used</value>
      <webElementGuid>e3612d91-d5c8-4881-8a01-479f3665845f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;superHeroBannerContainer&quot;)/div[@class=&quot;emdpnlj4 css-18eyk9p e11el9oi0&quot;]/div[@class=&quot;css-1b1a19r e1qqueke0&quot;]/div[@class=&quot;emdpnlj0 css-1ficdhs e1qqueke1&quot;]/a[@class=&quot;css-vyzx91 e1uau9z02&quot;]/span[@class=&quot;css-hwgv0r e1uau9z01&quot;]</value>
      <webElementGuid>d2b8cd51-04e4-4fb2-9976-4ceff646247d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='superHeroBannerContainer']/div[2]/div/div/a/span</value>
      <webElementGuid>5d30df9e-06a9-4ef8-a748-5169e3c1064a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelley Knows Cars'])[1]/following::span[1]</value>
      <webElementGuid>c50a2a82-d14e-462d-b312-d060cccdb0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Cars for Sale'])[1]/preceding::span[2]</value>
      <webElementGuid>d47eed5e-82e3-4044-9da4-0236ef32e0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>23857a59-d0f9-4c4c-aabb-bc165c7987e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Price New/Used' or . = 'Price New/Used')]</value>
      <webElementGuid>86b1c83d-f634-4cbb-92d8-eb21622773f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
