<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1c9af234-d62f-4c6e-8fea-98e1e4ad20f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/header/div/div/div[3]/a/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Di Động Việt - Chuyển giao giá trị vượt trội&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>461da00f-2f77-41cc-9ad8-4b47b9da329b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>230</value>
      <webElementGuid>0f0b48d8-fdf8-4778-ae6b-fd818d1560cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>54</value>
      <webElementGuid>1edc8141-1f69-416e-b051-e0f96ec2ab9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/svg/Header/logowhite.svg</value>
      <webElementGuid>8005a2dd-c9ad-48f2-85f2-b6c95cddbdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Di Động Việt - Chuyển giao giá trị vượt trội</value>
      <webElementGuid>9d8319d1-466e-4347-a530-86ee6fdf60e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_8248c3&quot;]/div[@class=&quot;relative bg-bgddv antialiased&quot;]/div[@class=&quot;z-0 w-full transition-all&quot;]/header[@class=&quot;page-header flex h-[95px] w-full min-w-full items-center justify-center max-md:h-[100px]&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;w-full items-center py-2      flex md:gap-x-8&quot;]/div[@class=&quot;max-md:w-4/6 md:w-2/6&quot;]/a[1]/div[@class=&quot;max-md:hidden&quot;]/img[1]</value>
      <webElementGuid>d746d281-73eb-4c11-8fa0-b274c8231711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/header/div/div/div[3]/a/div[2]/img</value>
      <webElementGuid>b195ac03-014d-4635-98ad-1bc4cf166abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Di Động Việt - Chuyển giao giá trị vượt trội'])[2]</value>
      <webElementGuid>6b6b90c7-50ed-4fe6-9ed9-f1ae36dfd5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>5ee645e5-d649-4d3c-a2a8-9715caea5a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/svg/Header/logowhite.svg' and @alt = 'Di Động Việt - Chuyển giao giá trị vượt trội']</value>
      <webElementGuid>f7cffae1-b5a2-48fb-afae-266e9ad954f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
