<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_1800.6018</name>
   <tag></tag>
   <elementGuidId>4ca1a0b9-03b9-41c8-b1df-3c2d41deda5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/header/div/div/div[6]/div/div/a/div/div[2]/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.title.text-lg.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Di Động Việt - Đặt hàng Đặt hàng 1800.6018&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0e6964a7-2e4b-4dbd-b991-ed46c37d01e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title text-lg text-white</value>
      <webElementGuid>45533c11-8aec-4e87-8972-c43cb93ffe66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1800.6018</value>
      <webElementGuid>1913baba-9f41-4591-ba45-7ef964611cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_8248c3&quot;]/div[@class=&quot;relative bg-bgddv antialiased&quot;]/div[@class=&quot;z-0 w-full transition-all&quot;]/header[@class=&quot;page-header flex h-[95px] w-full min-w-full items-center justify-center max-md:h-[100px]&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;w-full items-center py-2      flex md:gap-x-8&quot;]/div[@class=&quot;max-md:hidden max-md:col-span-1 md:w-3/6&quot;]/div[@class=&quot;flex w-full items-center justify-between max-md:hidden&quot;]/div[@class=&quot;w-1/5&quot;]/a[1]/div[@class=&quot;flex items-center justify-start menuhover&quot;]/div[@class=&quot;w-3/4 pl-2&quot;]/div[@class=&quot;justify-center items-center&quot;]/p[@class=&quot;title text-lg text-white&quot;]</value>
      <webElementGuid>2a6ac3ba-1f20-4f9d-bfe8-f696c110de83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/header/div/div/div[6]/div/div/a/div/div[2]/div/p[2]</value>
      <webElementGuid>8b603404-5dfe-4d61-afbc-be9f7b996f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/preceding::p[8]</value>
      <webElementGuid>ef3ea4b2-99c2-4bb1-9722-c966ba412755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[1]/preceding::p[8]</value>
      <webElementGuid>21e6db54-87be-43bc-9f9b-a7f6e857571b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1800.6018']/parent::*</value>
      <webElementGuid>8e0ef8a8-0b7e-4900-b726-7a928f3e8b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>70c12ee9-c687-4cfb-9180-2f98700cba80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '1800.6018' or . = '1800.6018')]</value>
      <webElementGuid>1f0c9f6a-154c-44b6-992f-a8ea06dbf0c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
