<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Do Not Sell My Personal Information</name>
   <tag></tag>
   <elementGuidId>05b12c2c-07a9-414d-8d2a-f9cc7d054284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='unstyled'])[162]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Do Not Sell My Personal Information&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>251f508b-55b4-4784-8243-01c44ad1e6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>undefinedfooter</value>
      <webElementGuid>3b899d5c-43e1-46ee-88cc-1891ccc29a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-partner</name>
      <type>Main</type>
      <value>nx</value>
      <webElementGuid>c9cebdf9-56d7-4154-9c63-4a1b89e1b284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag-id</name>
      <type>Main</type>
      <value>footerLinks2</value>
      <webElementGuid>dd15b6dd-b163-4c09-9797-6fbbd542ba46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/california-privacy-rights/</value>
      <webElementGuid>d783b155-7f6d-4375-a937-84e4e9ab2edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>unstyled</value>
      <webElementGuid>6790a65c-cf85-4ac5-a65e-121d369edd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>532baa8b-75fa-43d3-b3b9-42dd0adef204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1yukjqw e1ez57g00</value>
      <webElementGuid>9758b0f0-0d8f-42cd-8f3d-d481e62ed7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Do Not Sell My Personal Information</value>
      <webElementGuid>4c8125f4-ff41-43e5-975c-e7c5a1a0cefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalFooter&quot;)/div[@class=&quot;css-1vrab63&quot;]/div[@class=&quot;css-1nh907i&quot;]/a[@class=&quot;css-1yukjqw e1ez57g00&quot;]</value>
      <webElementGuid>1fa17546-dc95-4425-8964-c65c3e5841dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='unstyled'])[162]</value>
      <webElementGuid>b7164eb1-0577-406f-a9c4-5b0aea9b3bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='globalFooter']/div/div/a[3]</value>
      <webElementGuid>d9c4f1b6-f6f7-4ea4-bc4e-d99bc199345a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Do Not Sell My Personal Information')]</value>
      <webElementGuid>6344f772-b234-4896-8fe5-9c553fa27521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/following::a[1]</value>
      <webElementGuid>5393205e-99de-4668-ad7d-3202f6356967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::a[1]</value>
      <webElementGuid>1af579fb-5077-483e-a4f7-6c841e917d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[3]/preceding::a[1]</value>
      <webElementGuid>1509dfb3-c9b8-465a-8a11-7a354bfa1639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do Not Process My Sensitive Information'])[1]/preceding::a[1]</value>
      <webElementGuid>2a04dc0e-5408-45d8-b75e-22a208ecdfab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Do Not Sell My Personal Information']/parent::*</value>
      <webElementGuid>dc749695-b005-4294-aba5-f12c331d0537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/california-privacy-rights/')]</value>
      <webElementGuid>bd4ca5ec-230d-4373-b285-1323f9b6b042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a[3]</value>
      <webElementGuid>6445df9d-aa83-4002-b2dc-8f2eb377ddcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/california-privacy-rights/' and @type = 'unstyled' and (text() = 'Do Not Sell My Personal Information' or . = 'Do Not Sell My Personal Information')]</value>
      <webElementGuid>c09f9941-1517-4557-a724-51f1c92b4858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
