<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Do Not Process My Sensitive Information</name>
   <tag></tag>
   <elementGuidId>aca6ffdc-3b3b-4b2f-9076-f3e40265ea78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='unstyled'])[163]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Do Not Process My Sensitive Information&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf4b3b04-c708-4583-9463-449440bae715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>undefinedfooter</value>
      <webElementGuid>e46ab5bb-62da-4040-a728-8ee7132135a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-partner</name>
      <type>Main</type>
      <value>nx</value>
      <webElementGuid>1f2e1d59-ffad-4491-bd68-33f1f1c9134d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag-id</name>
      <type>Main</type>
      <value>footerLinks3</value>
      <webElementGuid>44844099-1a94-423c-ad7e-e24b862c007d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/california-privacy-rights/</value>
      <webElementGuid>83cd8f2c-d3e2-488e-ba1e-ef04c826b701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>unstyled</value>
      <webElementGuid>f104bb34-e920-4c43-b5b7-4b25020a453b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>5df8fe6e-702d-46d8-9e40-b3862fc0cecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1yukjqw e1ez57g00</value>
      <webElementGuid>2cb0d0e0-518f-4d08-a27f-461b8e258dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Do Not Process My Sensitive Information</value>
      <webElementGuid>3a7c075c-9552-48f8-853f-dfc209e1c6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalFooter&quot;)/div[@class=&quot;css-1vrab63&quot;]/div[@class=&quot;css-1nh907i&quot;]/a[@class=&quot;css-1yukjqw e1ez57g00&quot;]</value>
      <webElementGuid>360a6c01-92aa-4a19-97bf-874927e3b41d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='unstyled'])[163]</value>
      <webElementGuid>5df6f7f6-7991-413f-b63e-b4555b7730c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='globalFooter']/div/div/a[4]</value>
      <webElementGuid>78eb21ed-8c09-47d9-b617-f331ec5e2462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Do Not Process My Sensitive Information')]</value>
      <webElementGuid>1469305a-c3e0-4e5c-ac20-a66965c68cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[3]/following::a[1]</value>
      <webElementGuid>4e1e01d2-7ad2-48ab-b6e9-f6769754dae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do Not Sell My Personal Information'])[1]/following::a[1]</value>
      <webElementGuid>5ba80c3c-c572-48ca-91be-9f79c78b1f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[4]/preceding::a[1]</value>
      <webElementGuid>7853bdf7-fc98-4b7c-846f-089c9501a62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::a[1]</value>
      <webElementGuid>d5d1a1ff-8f1d-4831-b01e-0211c16760a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Do Not Process My Sensitive Information']/parent::*</value>
      <webElementGuid>f70dfc7b-bcb0-4b6f-a2f8-bda65510e679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/california-privacy-rights/')])[2]</value>
      <webElementGuid>dc1b311a-ef6f-4ad8-a792-47678383a8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a[4]</value>
      <webElementGuid>5cc6fd26-c4a8-4386-b4dd-5519c830f9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/california-privacy-rights/' and @type = 'unstyled' and (text() = 'Do Not Process My Sensitive Information' or . = 'Do Not Process My Sensitive Information')]</value>
      <webElementGuid>fad013d7-a940-49c3-bc61-6c97029bc4ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
