<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FacebookTwitterRSSLinkedInYouTube 1995-_981592</name>
   <tag></tag>
   <elementGuidId>aeb46b9c-7d77-4d5a-b6cd-d3c10226fc20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1m0r149</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='globalFooter']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;FacebookTwitterRSSLinkedInYouTube© 1995-2024 Kelley Blue Book Co.®, Inc. All rig&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f28cfb38-bef5-4832-bd94-df26ae8e9b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1m0r149</value>
      <webElementGuid>f952a6a4-8e3f-4947-a150-6d8da0f1a976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FacebookTwitterRSSLinkedInYouTube© 1995-2024 Kelley Blue Book Co.®, Inc. All rights reserved.Copyrights &amp; Trademarks|Vehicle Photos © Evox Images|Terms of Service|Privacy Policy|Linking Policy|Accessibility Statement|Manage Cookies</value>
      <webElementGuid>dcde462e-8173-42ef-ae42-bdee6d0de839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalFooter&quot;)/div[@class=&quot;css-1vrab63&quot;]/div[@class=&quot;css-1m0r149&quot;]</value>
      <webElementGuid>e4b11fad-da87-44e2-8131-3deba5604c4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='globalFooter']/div/div[2]</value>
      <webElementGuid>cb8de060-bf31-4176-bfd2-f198457cce74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KBB Canada'])[1]/following::div[1]</value>
      <webElementGuid>3c4afb04-cd12-434d-9d31-8e368d6a13ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[11]/following::div[1]</value>
      <webElementGuid>a471066c-6f9a-4e54-9d2b-717ea62fbadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]</value>
      <webElementGuid>7ac3253f-2729-42c4-9032-cfa8e929817e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'FacebookTwitterRSSLinkedInYouTube© 1995-2024 Kelley Blue Book Co.®, Inc. All rights reserved.Copyrights &amp; Trademarks|Vehicle Photos © Evox Images|Terms of Service|Privacy Policy|Linking Policy|Accessibility Statement|Manage Cookies' or . = 'FacebookTwitterRSSLinkedInYouTube© 1995-2024 Kelley Blue Book Co.®, Inc. All rights reserved.Copyrights &amp; Trademarks|Vehicle Photos © Evox Images|Terms of Service|Privacy Policy|Linking Policy|Accessibility Statement|Manage Cookies')]</value>
      <webElementGuid>57787132-c113-4c95-95c2-3b16678df62c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
