<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ATV Sport_AbtKbbLogo</name>
   <tag></tag>
   <elementGuidId>72bfbfe0-2fea-456e-b6d0-fc38181ff571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='AbtKbbLogo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AbtKbbLogo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Kelley Blue Book logo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>91ba3375-6798-414a-a73a-0ab1dd763b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AbtKbbLogo</value>
      <webElementGuid>09a44fe6-c18c-464a-b502-1085528c399c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://file.kbb.com/kbb/images/logos/KBBLogoRefresh.svg</value>
      <webElementGuid>687fd738-72b3-470e-b5de-2cb2164a9b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Kelley Blue Book logo</value>
      <webElementGuid>53088295-5e5c-4694-951e-986a509f8283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-ionjye</value>
      <webElementGuid>087d412c-6c73-46a1-8c68-cde7e4a2f138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AbtKbbLogo&quot;)</value>
      <webElementGuid>2e9c32b7-541e-4e68-ab7f-a65033d7ef19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='AbtKbbLogo']</value>
      <webElementGuid>48e9ff7d-309b-4838-817f-37652028aba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div[9]/div/div/div/div/div/img</value>
      <webElementGuid>82e848b7-d480-4674-b0cc-04b8da582f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Kelley Blue Book logo']</value>
      <webElementGuid>c8f9738b-b422-4c4c-b3fc-81df9ff95f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/img</value>
      <webElementGuid>a6da77cb-7a84-494d-840f-bbb1acbc6848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'AbtKbbLogo' and @src = 'https://file.kbb.com/kbb/images/logos/KBBLogoRefresh.svg' and @alt = 'Kelley Blue Book logo']</value>
      <webElementGuid>532fc90b-a024-4032-9139-87ab3e6e2e17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
